In [11]:
#creating numpy/n-d arrays
import numpy as np

In [12]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [13]:
type(arr1)

numpy.ndarray

In [14]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr5=np.identity(5)

In [18]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr7=np.arange(5,16)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
arr8=np.arange(5,16,2)
arr8

array([ 5,  7,  9, 11, 13, 15])

In [23]:
arr9=np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [24]:
arr10=arr9.copy()
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])