In [79]:
import numpy as np

In [80]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [81]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [82]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [83]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [84]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [85]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [86]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [87]:
arr1.dot(arr2)

154

In [88]:
arr1.dot(arr3)

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [89]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [90]:
arr4.max()

11

In [91]:
arr4.min()

6

In [92]:
arr4.min(axis=0)

array([6, 7])

In [93]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [94]:
arr4.sum()

51

In [95]:
arr4.sum(axis=0)

array([24, 27])

In [96]:
arr4.mean()

8.5

In [100]:
np.median(arr4)

8.5

In [101]:
arr4.std()

1.707825127659933

In [102]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [103]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])