In [40]:
import numpy as np

In [41]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [42]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [43]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [44]:
arr4.max()

11

In [45]:
arr4.min()

6

In [46]:
arr4.min(axis=0)

array([6, 7])

In [47]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [48]:
arr4.sum()

51

In [49]:
arr4.sum(axis=0)

array([24, 27])

In [50]:
arr4.mean()

8.5

In [51]:
np.median(arr4)

8.5

In [52]:
arr4.std()

1.707825127659933

In [53]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [54]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [55]:
arr4.ndim

2

In [56]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [57]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [58]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [59]:
arr5=np.arange(12,18).reshape(2,3)

In [60]:
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [61]:
np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [62]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [63]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]