Indexing With Boolean Arrays

In [67]:
import numpy as np

In [69]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[63, 35, 87, 66, 86],
       [46,  8, 37, 79, 23],
       [ 3, 23, 73, 77, 12],
       [45, 96, 14, 83, 88]])

In [70]:
arr[0]

array([63, 35, 87, 66, 86])

In [71]:
arr[0][2]

87

In [72]:
arr>50

array([[ True, False,  True,  True,  True],
       [False, False, False,  True, False],
       [False, False,  True,  True, False],
       [False,  True, False,  True,  True]])

In [73]:
(arr>50).shape

(4, 5)

In [74]:
arr[arr>50]

array([63, 87, 66, 86, 79, 73, 77, 96, 83, 88])

In [76]:
#Greater than 50 and odd
arr[(arr>50) & (arr%2!=0)]

array([63, 87, 79, 73, 77, 83])

In [77]:
arr[(arr>50) & (arr%2!=0)]=0

In [78]:
arr

array([[ 0, 35,  0, 66, 86],
       [46,  8, 37,  0, 23],
       [ 3, 23,  0,  0, 12],
       [45, 96, 14,  0, 88]])