In [11]:
#creating numpy/n-d arrays
import numpy as np

In [12]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [13]:
type(arr1)

numpy.ndarray

In [14]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr5=np.identity(5)

In [18]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr7=np.arange(5,16)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
arr8=np.arange(5,16,2)
arr8

array([ 5,  7,  9, 11, 13, 15])

In [23]:
arr9=np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [24]:
arr10=arr9.copy()
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [25]:
arr1

array([1, 2, 3, 4, 5])

In [26]:
arr1.shape

(5,)

In [28]:
arr2.shape

(2, 3)

In [30]:
arr11=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr11

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
arr11.shape

(2, 2, 2)

In [32]:
arr11.ndim

3

In [33]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr2.ndim

2

In [35]:
arr1

array([1, 2, 3, 4, 5])

In [36]:
arr1.ndim

1

In [37]:
arr1.size

5

In [38]:
arr11

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [42]:
arr11.size

8

In [43]:
arr11.itemsize

8

In [45]:
arr10.itemsize

8

In [47]:
arr10.dtype

dtype('float64')

In [48]:
arr11.dtype

dtype('int64')

In [49]:
arr11.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])