In [167]:
import numpy as np

In [168]:
np.random.random()

0.9033795205622538

In [169]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [170]:
np.random.uniform(1,100)

72.31212485077366

In [171]:
np.random.uniform(1,100,10).reshape(2,5)

array([[ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093],
       [35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054]])

In [172]:
np.random.randint(1,10)

3

In [173]:
np.random.randint(1,10,5)

array([5, 8, 8, 2, 8])

In [174]:
np.random.randint(1,10,15).reshape(3,5)

array([[1, 7, 8, 7, 2],
       [1, 2, 9, 9, 4],
       [9, 8, 4, 7, 6]])

In [175]:
a=np.random.randint(1,10,6)
a

array([2, 4, 5, 9, 2, 5])

In [176]:
np.max(a)

9

In [177]:
np.min(a)

2

In [178]:
np.argmax(a)

3

In [179]:
a[np.argmax(a)]

9

In [180]:
a[np.argmin(a)]

2

In [181]:
np.argmin(a)

0

In [182]:
a=np.random.randint(1,10,6)
a

array([1, 4, 3, 1, 5, 3])

In [183]:
a[a%2==1]=-1
a

array([-1,  4, -1, -1, -1, -1])

In [184]:
a=np.random.randint(1,50,6)
a

array([24,  8, 27, 26, 41, 23])

In [186]:
np.where(a%2==1,-1,a)

array([24,  8, -1, 26, -1, -1])

In [187]:
a

array([24,  8, 27, 26, 41, 23])

In [188]:
out=np.where(a%2==1,-1,a)
out

array([24,  8, -1, 26, -1, -1])

In [189]:
a=np.random.randint(1,50,10)
a

array([10,  4, 40, 24, 37, 28, 38, 20, 39,  9])

In [190]:
a=np.sort(a)
a

array([ 4,  9, 10, 20, 24, 28, 37, 38, 39, 40])

In [191]:
np.percentile(a,25)

12.5

In [192]:
np.percentile(a,50)

26.0

In [193]:
np.percentile(a,99.8)

39.982